### PR TITLE
Fix public server verified badge classes

### PR DESCRIPTION
**Pull request by FedeIlLeone**
This PR fixes the verified badge found in BD's public servers list by replacing the classes.

~I don't think it's a good thing to have hard-coded classes, it could be done by getting the classes from the corresponding modules, but I don't know whether to do it or not, I wait for feedback.~

Before -> After
bef-aft

### CODE REVIEW

**Review by Strencher — CHANGES_REQUESTED** [review]
Instead of harccoding the className once again, you should copy the css rules and make our own styles.

**Comment by FedeIlLeone** [comment]
I have replaced all classes, should be ok now.

**Comment by Bettlee** [comment]
> Instead of harccoding the className once again, you should copy the css rules and make our own styles.

Honestly, it just sounds like someone's lazy

**Comment by rauenzi** [comment]
Comments like this are entirely unnecessary and counter-productive @Bettlee Please refrain in the future.

**Comment by Bettlee** [comment]
> Comments like this are entirely unnecessary and counter-productive @Bettlee Please refrain in the future.

Sure thing

**Pull request closed without merging**
