### PR TITLE
Check for possible installation dirs on Linux

### PR DESCRIPTION
**Pull request by octoman90**
Discord may be installed in different directories depending on the Linux distro. Check for a list of possible ones when injecting.

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
Missing support for Fedora (`/usr/lib64`); as well as Snap, Flatpak, and NixOS whose paths are dynamic.

**Review by ObserverOfTime — CHANGES_REQUESTED** [review]
Missing support for Fedora (`/usr/lib64`); as well as Snap, Flatpak, and NixOS whose paths are dynamic.

**Comment by octoman90** [comment]
> Missing support for Fedora (`/usr/lib64`); as well as Snap, Flatpak, and NixOS whose paths are dynamic.

I can't check and test every distro, package manager and repository, but I can offer a piece of code that has the idea of supporting them. It is easily extendable and, IMO, adding other possible directories to the array should be done in separate pull requests.

**Comment by ObserverOfTime** [comment]
Your PR doesn't specify that the change is only useful for Gentoo (and, incidentally, Arch).

You could, at the very last, add the Fedora directory as well.

**Comment by octoman90** [comment]
> Your PR doesn't specify that the change is only useful for Gentoo (and, incidentally, Arch).
> 
> You could, at the very last, add the Fedora directory as well.

I guess it won't hurt adding it for now, even if it turns out to be the wrong directory.

**Pull request closed without merging**
