### PR TITLE
Updated italian translation

### PR DESCRIPTION
**Pull request by maicol07**

### CODE REVIEW

**Comment by SmolAlli** [comment]
To add languages, please use https://poeditor.com/join/project?hash=nRljcnV0ET

**Comment by maicol07** [comment]
@SmolAlli for some reason, I can't select Italian in POEditor when joining the project

**Comment by rauenzi** [comment]
If you have not been setup on POEditor, please reach out

**Comment by maicol07** [comment]
> If you have not been setup on POEditor, please reach out

I haven't been able to signup on POEditor. My language is uncheckable

**Comment by maicol07** [comment]
@rauenzi I've joined the project on POEditor. Now waiting the approval

**Comment by maicol07** [comment]
@rauenzi it's still on pending...

**Pull request closed without merging**
