### PR TITLE
Add custom `-bd-accent-color` css value

### LINKED ISSUE #970: [Feature] Add a way for theme to get windows accent colour
**Is your feature request related to a problem? Please describe.**
Currently I'm trying to make a windows look theme for discord but I cant pull the accent colour from windows to make it dynamic like other windows apps.

**Describe the feature you'd like**
Mabey make a variable so that theme can use it like var(--winAccent)

### PR DESCRIPTION
**Pull request by TheCommieAxolotl**
Closes #970.

Adds a special `--os-accent-color` variable that themes/customcss can use.

e.g.
```css
:root {
	--theme-accent: var(--os-accent-color);
}
```

### CODE REVIEW

**Comment by TheCommieAxolotl** [comment]
Video Preview:

https://github.com/BetterDiscord/BetterDiscord/assets/87679354/a94a7850-76d8-49b4-bd8f-94a6dc4a0d77

**Comment by rauenzi** [comment]
I understand why you prefixed it with `-bd` but I think the name is a bit misleading. Maybe something like `--os-accent-color`. I also think it would be better to just add a snippet like this

```css
:root {
   --os-accent-color: <result of ipc>;
}
```
rather than trying to manually process and replace every css added through the DOM manager as that adds additional overhead (and makes it unexpectedly asynchronous) and does not catch all cases.

**Comment by TheCommieAxolotl** [comment]
I've updated it to do that, the only issue is that there might be a noticeable delay before the colour "loads" as it's executing after the rest of the startup process however that would only be a problem if a theme used this value extensively.

**Comment by rauenzi** [comment]
Yeah that's a fair point, and I don't have a problem with it being moved to before themes in the core order and done via `then` so we don't necessarily have to wait. 

```js
IPC.getSystemAccentColor().then(value => DOMManager.injectStyle("bd-os-values", `:root {--os-accent-color: ${value}));
```

Or is there something else that prevents us from doing it that early?

I also thought about whether this should be a user setting, but I think making it a setting would end up with too much inconsistency.


My only other thought is, what do you think about returning `""` as default value instead of `#000000` so themes can make use of variable fallback (`var(--os-accent-color, #f0f0ff)`)? Or maybe `#000000` is an electron defined default thing.

**Comment by TheCommieAxolotl** [comment]
> I also thought about whether this should be a user setting, but I think making it a setting would end up with too much inconsistency.

That could be done, but yes I do agree it would add a level of complexity.

**Comment by rauenzi** [comment]
Yeah if you think it's not worth it then let's not bother. It LGTM otherwise.

**Comment by rauenzi** [comment]
Actually I think there's a typo in the css being injected, is there no closing bracket for the `:root`? I probably did that above too 😅

**Pull request merged**
