### PR TITLE
Fix fetch

### PR DESCRIPTION
**Pull request by bottomtext228**
Fixes FetchOptions missing timeout property.

Fixes timeout property in options was not used when using `BdApi.Net.fetch`.

Fixes  `TypeError: Failed to construct 'Response': Response with null body status cannot have body` when making a request with `BdApi.Net.fetch` and response answer has a status code (101, 204, 205, 304) that must not have a body.

Fixes `Uncaught Error: Cannot pipe, not readable` when piping response with `require('request')` (It is deprecated module but why not)
```JS
const request = require('request').get(url, (error, res, body) => {
         
 });

const stream = require('fs').createWriteStream('data.txt');
      
request.pipe(stream); // Uncaught Error: Cannot pipe, not readable
```

### CODE REVIEW

**Comment by rauenzi** [comment]
We actually don't want to fix the polyfill going forward as we are deprecating it in favor of the new `fetch` request (and deprecating all node polyfills).

Rest of review should be looked at by @Strencher

**Comment by rauenzi** [comment]
Please remove the change to [preload/src/api/https.js](https://github.com/BetterDiscord/BetterDiscord/pull/1671/files#diff-f44f684cd72f03011e5af524946ec8222ae4fe75a62b1fd4c4b0484bd29e54d2)

**Comment by bottomtext228** [comment]
Done

**Comment by resendayter** [comment]
what is this program

**Comment by resendayter** [comment]
suka

**Pull request merged**
