### PR TITLE
Added React Store display names to byDisplayName Filter

### PR DESCRIPTION
**Pull request by LuckyMika**
The "byDisplayName" Filter now supports react store names

### CODE REVIEW

**Comment by TheCommieAxolotl** [comment]
I see a few scenarios where blindly calling `m.getName` might lead to some unintended behavior. You might want to check if the module is a store by making sure `m._dispatchToken` exists.

**Comment by TypekitMapping** [comment]
BetterDiscord is really good! But Vencord is better

**Comment by LuckyMika** [comment]
I think that is actually a good idea and I will add that.

**Review by Diegiwg — APPROVED** [review]

**Comment by rauenzi** [comment]
I overall don't think this is a good idea. A display name refers to a specific property meant for react components. These days it's not _as_ useful due to the mangling, but it is still a misnomer to apply it to the internal stores.

**Pull request closed without merging**
