### PR TITLE
Update issue templates to forms

### PR DESCRIPTION
**Pull request by TheChilliPL**
Changes classic issue templates to new forms that are easier to use.

<details><summary>Click here to show a comparison of the bug report template.</summary>

**Old:**
image
**New:**
image

</details>

### CODE REVIEW

**Comment by Farcrada** [comment]
Credit where credit is due; thank you for this idea.

That looks very nice, and way better than markdown.

**Comment by rauenzi** [comment]
Very nice! When did they add this?

**Comment by dav1312** [comment]
Probably recently, they are still in beta
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by TheChilliPL** [comment]
Not sure when they added that exactly, but I spotted it when reporting an issue today and it seems like an amazing feature.
It is still in beta, but working fine. It's your choice if it's worth adding now or waiting until it goes “stable”

**Comment by dav1312** [comment]
Sometimes the bug reports opened in this repo are not caused by BetterDiscord but by a plugin for example.
Something like this could be added.
```yml
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: By submitting this issue I made sure that this bug is caused and related to the BetterDiscordApp and not to a plugin, theme, the BetterDiscord Installer or the BetterDiscord Documentation.
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
```
image

**Comment by rauenzi** [comment]
@TheChilliPL please consider the above from @dav1312

**Pull request closed without merging**
