### PR TITLE
Lazy load sidebar header

### LINKED ISSUE #1529: [Bug] Discord Crashing by open Settings
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a plugin or theme

### Describe the Bug

No Plugins or theme installed

### Expected Behavior

Open settings

### Steps To Reproduce

1.Open Settings in Discord
2.Crash

### Operating System

Windows

### Discord Version

Stable

### BetterDiscord Version

v1.8.4

### Anything else?

https://youtu.be/e9CvPZoDoTM

Workaround : Rightclick the settings

Error : 
```
dba4fb0b04a3f8198c97.js:152 TypeError: Cannot read property 'Header' of undefined
    at he.render (<anonymous>:4:119159)
    at Cs (71e2907e1982c4e4e19e.js:1623)
    at Rs (71e2907e1982c4e4e19e.js:1622)
    at yu (71e2907e1982c4e4e19e.js:1663)
    at Oc (71e2907e1982c4e4e19e.js:1655)
    at Ic (71e2907e1982c4e4e19e.js:1655)
    at hc (71e2907e1982c4e4e19e.js:1654)
    at ic (71e2907e1982c4e4e19e.js:1651)
    at oc (71e2907e1982c4e4e19e.js:1650)
    at g (71e2907e1982c4e4e19e.js:1772)
    at L (71e2907e1982c4e4e19e.js:1773)
    at t.exports (dba4fb0b04a3f8198c97.js:21)
    at g.<computed> (dba4fb0b04a3f8198c97.js:36)
    at Number.m (dba4fb0b04a3f8198c97.js:36)
    at MessagePort.b (dba4fb0b04a3f8198c97.js:36)

### PR DESCRIPTION
**Pull request by Strencher**
Lazy loads the sidebar header because discord started to lazy load their settings layers including the components for it. 

Closes #1529

### CODE REVIEW

**Review by JellyBrick — APPROVED** [review]

**Comment by rauenzi** [comment]
Does this work equivalent to the original? If so why not just use custom component all the time?

**Comment by Strencher** [comment]
> Does this work equivalent to the original? If so why not just use custom component all the time?

It does, I just want to maintain the original component to maintain the class names etc for themes compatibility. If you want me to class names instead, let me know.

**Review by rauenzi — APPROVED** [review]

**Comment by arhamepic101** [comment]
How do I install this? I am confused on how to use this code to fix my problem. I would appreciate it a lot if someone was to help me. Thanks!

**Comment by Abelomar** [comment]
> How do I install this? I am confused on how to use this code to fix my problem. I would appreciate it a lot if someone was to help me. Thanks!

Same! I have no idea where those codes go or how to access that location. Any help will be appreciated.

**Comment by Inbestigator** [comment]
> > How do I install this? I am confused on how to use this code to fix my problem. I would appreciate it a lot if someone was to help me. Thanks!
> 
> Same! I have no idea where those codes go or how to access that location. Any help will be appreciated.

The fixes .exe is not released yet, be patient.

**Pull request merged**
