### PR TITLE
Add Notices API.

### PR DESCRIPTION
**Pull request by Strencher**
Adds a simple notices api for plugins/bd. 

Maybe consider adding this to the Wiki since i can't PR for that.

EDIT: This is how notices look right now. 
image

### CODE REVIEW

**Comment by dav1312** [comment]
Why not use Discord's colors?

```css
.bd-notice-info {
    --color: #5865f2;
}

.bd-notice-success {
    --color: #3ba55d;
}

.bd-notice-warning {
    --color: #faa81a;
}

.bd-notice-error {
    --color: #ed4245;
}
```

**Comment by Strencher** [comment]
I was going off the current toast colors which are apparently discord's old colors.

**Comment by dav1312** [comment]
They use the new colors for notices like these
image

**Comment by QbDesu** [comment]
As I mentioned before maybe returning a function to close the notice would be a nice idea.
Also adding the detail that the button callback already receives the close function as a parameter to the docs comment (and the comment also referrs to it as Toast in one place)

**Comment by Strencher** [comment]
Alright, i exposed the `closeNotification` function for the caller. I also updated the colors as david suggested and fixed a little bug with the border at the top left. Another thing i added is an option to immediately close the notification without adding a closing class.

**Comment by rauenzi** [comment]
Strencher can you address Qb's review?

**Pull request merged**
