### PR TITLE
Update zh-tw.json

### PR DESCRIPTION
**Pull request by Neo1102**
Hi
I fixed some wrong string in zh-tw. json
Plz refer
tks

### CODE REVIEW

**Comment by SmolAlli** [comment]
Please refer to the [Contributing Guide](https://github.com/BetterDiscord/BetterDiscord/blob/main/CONTRIBUTING.md#translations) for the correct way to submit translations for the BetterDiscord project.

**Comment by Neo1102** [comment]
> Please refer to the [Contributing Guide](https://github.com/BetterDiscord/BetterDiscord/blob/main/CONTRIBUTING.md#translations) for the correct way to submit translations for the BetterDiscord project.

got it
thx

**Comment by rauenzi** [comment]
https://github.com/BetterDiscord/BetterDiscord/blob/main/CONTRIBUTING.md#translations

**Comment by Neo1102** [comment]
Can someone approve project access for me?
Name : ИEØ_ΙΙØZ
Access language : Traditional Chinese

**Pull request closed without merging**
